### ISSUE TITLE
PumpTweet produces >140 character Tweet

### ISSUE THREAD

**Issue by strugee** [dper/pumptweet#28]
For whatever reason, [this note][1] produces a Tweet that's over 140 characters, and is thus rejected from Twitter.

 [1]: https://pump.strugee.net/alex/note/sy0I773nStaNT82IYkiQqA

**Comment by dper** [comment]
The text of the note is...

<blockquote>After implementing HTTP Strict Transport Security last week, I just did an SSL Labs test on strugee.net. I'm proud to say that I've finally achieved an A+ grade, and not only that, the configuration that got me that grade is shared among &lt;i&gt;all&lt;/i&gt; strugee.net subdomains!&lt;br&gt;Woot woot for web security!</blockquote>

That's 303 characters.  If the HTML is stripped (doing this by copy/pasting the text into a text editor, not inside of PumpTweet), it drops to 293 characters.

**Comment by dper** [comment]
Right now I'm getting errors with pumptweeet probably related to the microca.st certificate being expired. Until the certificate is fixed (long time?) or I make another account elsewhere (more likely), I can't get moving on this one. :-/

**Comment by strugee** [comment]
@dper no worries. I may try to send patches for this myself in the next couple days, depending on my schedule.

**Comment by dper** [comment]
Testing using the Twitter web interface.  Inside of pumptweet, the following shortened message is produced.

> After implementing HTTP Strict Transport Security last week, I just did an SSL Labs test on strugee.net. I'm pr… https://microca.st/dper/note/L-e2GIb_TjyiI3Mf9Pk9_g

It's 164 characters and cannot be posted.  The web interface says that I'm 8 characters too long.  The trailing URL gets shortened automatically by Twitter.  Let's see how this affects the length.  The URL would become something like `https://t.co/1234567890`.  Twitter's shortened URLs are 23 characters in length.  After shortening, it would look like ...

> After implementing HTTP Strict Transport Security last week, I just did an SSL Labs test on strugee.net. I'm pr… https://t.co/1234567890

This is 136 characters and ought to be tweet-able, but still we're over the character limit according to the error message.  In the web interface, it looks like Twitter is trying to shorten the other URL, `strugee.net`.  (I don't remember this happening in the past, so perhaps the Twitter devs have changed how they handle URLs recently.)  If `strugee.net` is shortened, it becomes something like `http://t.co/1234567890`.  The resulting message then becomes ...

> After implementing HTTP Strict Transport Security last week, I just did an SSL Labs test on http://t.co/1234567890. I'm pr… https://t.co/1234567890

This has 147 characters, which is 8 characters over the limit, just as the Twitter web interface shows.  So, the underlying cause of the problem is that some URLs are "shortened" by Twitter but actually become longer when that occurs, and at the moment PumpTweet does not handle this properly.

**Comment by dper** [comment]
Twitter sees `strugee.net` and decides it's a URL. The ideal solution is for PumpTweet to see that it's a URL, too, and shorten the note to compensate for the lost space as needed. How can that easily be done?

A good thing would be to use a library that can do this, but if said library doesn't identify URLs in exactly the same way as Twitter, we could see errors in the future.  For example, Twitter is finding URLs that don't begin with `http` or `https`, so a simple regex is not good enough.

Another possibility is to catch Twitter error messages about exceeding maximum length and crop those tweets more before trying to repost.  This is kind of hackish, but it has the advantage of using Twitter to decide if a message needs more shortening.

**Comment by dper** [comment]
Another possibility is this...  When posting to Twitter, right now each note becomes one tweet.  But the API for Twitter lets us post a message such that it is split into multiple tweets as necessary.  Right now we're not doing that, because the goal is one tweet per note.

This multi-tweet option could be enabled very easily.  It doesn't feel like the right solution, but it's so easy to implement that it's worth noting here.

**Comment by dper** [comment]
Information about the python-twitter API can be found at https://pypi.python.org/pypi/python-twitter or by calling `$ pydoc twitter.Api`.

**Comment by strugee** [comment]
If it's super easy, maybe we should add a config key for it?

**Comment by dper** [comment]
@strugee I think we can change the default to "show error message but move on", and add a "--halt-on-twitter-error" optional argument that will do what it sounds like. Then we can debug it easily in the future, and it won't make everything fail for normal use now.

The issue is one that the upstream library, `python-twitter`, should ideally handle. Their library has the same problem we do -- shortening actually means lengthening, so we hit the character limit -- and if we're lucky perhaps they will come up with a solution so we don't have to. Dunno. :-)

**Comment by strugee** [comment]
`--halt-on-twitter-error` sounds good to me. Other than that, I think we should just wait to see what the `python-twitter` folks say.

**Comment by dper** [comment]
I went with a more generic `--halt_on_error` argument.  This only affects behavior when Twitter produces errors when posting tweets.  All other errors result in the script halting, as they always have.

This partly fixes the issue. At least, it fixes it enough for now. Re-open later as needed.

**Comment by dper** [comment]
This has been fixed [upstream](https://github.com/bear/python-twitter/commit/a6f7e734941539f6c72f4cce4a76e8264fa80f79).  In that commit, python-twitter redoes length calculations to properly consider what URLs might get lengthened-when-shortened.  When python-twitter gets a new release, I'll move pumptweet to the new version, and that will be that.

**Comment by strugee** [comment]
@dper fantastic, thanks for driving this! (And the project in general!)
